### ISSUE TITLE
Buttersink causes lock up on Kernel 4.17

### ISSUE THREAD

**Issue by ceremcem** [AmesCornish/buttersink#62] opened 2018-08-05 23:59 UTC
On Debian Buster, (4.17, amd64), buttersink causes lock up. After Ctrl+C or even a reboot, btrfs-cleaner stuck at 100% cpu. 

Only way to workaround is `btrfs quota disable /`. 

I need to state that this situation is valid for my laptop (which I'm using for a long time) and the freshly installed and upgraded server (server is locked up the same way and I needed to re-install it). 

This behavior is not true (things work as normal) for Debian Stretch 4.9.0-7-amd64. I'm not sure if this is a kernel related issue or not.

**Comment by eugene-bright** [comment] 2018-08-08 12:41
Duplicate of previously closed #38

**Comment by eugene-bright** [comment] 2018-08-08 12:46
Version that is capable in some cases to work without quotas is presented in commit #60. I use it as a temporary solution.

**Comment by AmesCornish** [comment] 2018-10-03 21:28
Closing because I believe this is a btrfs issue.  The work-around is being tracked in #60 .

**Closed as completed by AmesCornish** 2018-10-03 21:28 UTC
